spring:
  application:
    name: soqqer
  datasource:
    url: jdbc:postgresql://localhost:5432/soqqer
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect