spring:
  application:
    name: soqqer
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/soqqer}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect