CREATE TABLE match_players
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    match_id    BIGINT                                  NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    team        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_match_players PRIMARY KEY (id)
);

CREATE TABLE matches
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    team_one_score INTEGER                                 NOT NULL,
    team_two_score INTEGER                                 NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

ALTER TABLE match_players
    ADD CONSTRAINT uk_match_players_match_employee UNIQUE (match_id, employee_id);

ALTER TABLE match_players
    ADD CONSTRAINT FK_MATCH_PLAYERS_ON_MATCH FOREIGN KEY (match_id) REFERENCES matches (id);

ALTER TABLE match_players
    ADD CONSTRAINT fk_match_players_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE;

ALTER TABLE match_players
    ADD CONSTRAINT fk_match_players_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

CREATE INDEX idx_match_players_match_id ON match_players (match_id);
CREATE INDEX idx_match_players_employee_id ON match_players (employee_id);